import Navbar from '@app/components/Navbar';
import { Montserrat } from 'next/font/google';
import './globals.css';

const mont = Montserrat({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={mont.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
